# Generated by Django 6.0 on 2025-12-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sal',
        ),
    ]
